### ISSUE TITLE
Support for Google Scholar?

### ISSUE THREAD

**Issue by jjcchh** [belaviyo/dark-theme#16]
Any plans to extend Google Dark Theme to Google Scholar (this would be awesome)?

**Comment by belaviyo** [comment]
Should be fixed by 0.3.0 release. You can try in on FF for now. Thanks for the report.

**Comment by LinuxOnTheDesktop** [comment]
Unfortunately there are problems with how the extension renders Google Scholar. Here's a screenshot (using Windows 10, Firefox 122.0, and version 0.6.3 of the extension):

![image](https://github.com/belaviyo/dark-theme/assets/47056543/f75ed22b-09e1-4cd8-82b2-fb28e50d87da)

Note the near-illegibility of the large word 'scholar' and the illegibility of the text that turns out to be read, 'Go to Google Scholar'.

Thank you for your work.
